/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;

/**
 *
 * @author Lenovo
 */
public class VentanaPrincipal extends javax.swing.JFrame {
     JLabel etinum1;
     JLabel etinum2;
     JTextField txtNum1; 
     JTextField txtNum2;
     JButton btnSumar;
     JButton btnRestar;
     
   //  * Creates new form VentanaPrincipal
   //  */
    public VentanaPrincipal() {
       initComponents();
       CreacionVentana();
    } 
    
    public void CreacionVentana(){
        this.setTitle("Programa Operaciones");
        this.setSize(500, 300);
        this.setLocation(100, 100);
        
        etinum1 = new JLabel();
        etinum1.setText("Numero 1:");
        etinum1.setBounds(10, 10,100, 20);
        this.getContentPane().add(etinum1);
        
        
        etinum2 = new JLabel();
        etinum2.setText("Numero 2:");
        etinum2.setBounds(10, 60,100, 20);
        this.getContentPane().add(etinum2);
        
        txtNum1 = new JTextField();
        txtNum1.setText("0");
        txtNum1.setBounds(110, 10, 100, 25);
        this.getContentPane().add(txtNum1);
        
        txtNum2 = new JTextField();
        txtNum2.setText("0");
        txtNum2.setBounds(110, 60, 100, 25);
        this.getContentPane().add(txtNum2);
        
        btnSumar = new JButton();
        btnSumar.setText("Sumar");
        btnSumar.setBounds(10, 120, 110, 25);
        this.getContentPane().add(btnSumar);
        
         btnRestar = new JButton();
         btnRestar.setText("Restar");
         btnRestar.setBounds(150, 120, 110, 25);
        this.getContentPane().add(btnRestar);
        ///Eventos desde codigo 22
        
               btnSumar.addActionListener(new ActionListener() {
          
            public void actionPerformed(ActionEvent evt) {
                btnSumarActionPerformed(evt);
            }
                private void btnSumarActionPerformed(ActionEvent evt) {
                double a,b,s;
        
              a=Double.parseDouble(txtNum1.getText());
              b=Double.parseDouble(txtNum2.getText());
              s=a+b;
              JOptionPane.showMessageDialog(null,"La resta es "+s);
                
            }
            

            
        });
       
            btnRestar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnRestarActionPerformed(evt);
            }

            private void btnRestarActionPerformed(ActionEvent evt) {
                double a,b,r;
        
              a=Double.parseDouble(txtNum1.getText());
              b=Double.parseDouble(txtNum2.getText());
              r=a-b;
              JOptionPane.showMessageDialog(null,"La resta es "+r);

                
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        });
   
       
    }
    

    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
